version: '3.4'

services:
  mysql:
    image:
      mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "keycloak"
      MYSQL_DATABASE: "keycloak"
      MYSQL_USER: "keycloak"
      MYSQL_PASSWORD: "keycloak"
    volumes:
      - db-data:/var/lib/mysql:rw
  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - 8080:8080
    depends_on:
      - mysql
volumes:
  db-data: