### Get endpoints
GET http://keycloak:8080/auth/realms/unleash/.well-known/openid-configuration
Accept: application/json

### Get token endpoint in `token_endpoint`
POST http://keycloak:8080/auth/realms/unleash/protocol/openid-connect/token?
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=unleash&username=unleashtest&password=unleashtest