# MUST BE ENABLED Direct auth flows for "unleash-web" client.
# Secret not required

### Get token endpoint in `token_endpoint`
POST http://keycloak:8080/realms/unleash/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=unleash-web&username=admin&password=admin&scope=openid%20email%20profile

> storeAndPrintJWT.js

### Get User Info
GET http://keycloak:8080/realms/unleash/protocol/openid-connect/userinfo
Authorization: Bearer {{access_token}}