### OIDC Configuration
GET http://keycloak:8080/realms/unleash/.well-known/openid-configuration
Accept: application/json

### JWK / Cervificates
GET http://keycloak:8080/realms/unleash/protocol/openid-connect/certs
Accept: application/json